Repository Elzian-Agro/Agro, pull requests merged in 2021-11, with the labels that each got.

#19 Add login button
  AgroEagel.html
  AgroMate.html
  about.html
  catalog.html
  contact.html
  css/navstyle.css
  css/style.css
  images/logo-black.png
  images/logo-white.png
  images/mate/3926345-middle.png
  index.html
  js/custom.js
  js/slide.js
Labels: bug, enhancement

#20 Added the Agromate webpage
  AgroMate.html
  about.html
  catalog.html
  contact.html
  images/Agro-mate.png
  index.html
Labels: bug, enhancement

#21 Added contents to the Agro-Eagle webpage
  AgroEagel.html
  AgroMate.html
  about.html
  catalog.html
  contact.html
  css/style.css
  images/agro-eagle-drone-image.png
  index.html
Labels: enhancement

#22 Changed contents in Agro-guard home page and about. Also added Agro-g…
  AgroEagel.html
  AgroGuard.html
  AgroMate.html
  about.html
  catalog.html
  contact.html
  css/style.css
  images/agro-guard-home.png
  images/agro-guard-pp.png
  images/crop-wastage.png
  images/early-prediction.png
  images/eco-friendly.png
  images/home-bg.png
  images/pest-predict.png
  images/pest-report.png
  images/pesticide.png
  index.html
Labels: documentation, enhancement

#30 About Us Webpage Improvements
  about.html
  css/style.css
  images/UNSDG-12.png
  images/UNSDG-13.png
  images/UNSDG-2.png
  images/UNSDG-8.png
Labels: bug, enhancement

#35 main branch changes
  css/style.css
Labels: enhancement

#38 About Us Page Improved
  about.html
  css/style.css
  images/building.png
  images/card.png
  images/coins.png
  images/paddy.png
  images/rotation.png
Labels: bug, documentation, enhancement

#39 Blog page created
  AgroEagel.html
  AgroGuard.html
  AgroMate.html
  about.html
  blog/blog-page.html
  catalog.html
  contact.html
  css/style.css
  images/smart-agriculture.png
  index.html
Labels: enhancement, good first issue

#41 Blog correction
  blog/blog-page.html
  css/style.css
  images/lilan.png
  js/main.js
Labels: bug

#42 checked the cdn links
  blog/blog-page.html
Labels: question
