Repository Elzian-Agro/Agro, pull requests merged in 2021-12, with the labels that each got.

#44 Career page deployment
  AgroEagel.html
  AgroGuard.html
  AgroMate.html
  about.html
  blog/blog-page.html
  career.html
  catalog.html
  contact.html
  css/style.css
  images/career-transformation.png
  images/career-workasfamily.png
  index.html
  js/main.js
Labels: bug, enhancement, good first issue

#46 Did All the changes and added necessary requirements with responsiveness
  AgroEagel.html
  AgroGuard.html
  AgroMate.html
  about.html
  blog/blog-main.html
  blog/blog-page-2.html
  blog/blog-page.html
  career.html
  catalog.html
  contact.html
  css/style.css
  index.html
Labels: bug, documentation, enhancement

#48 Added sitemap.xml file
  .gitignore
  sitemap.xml
Labels: enhancement

#49 Generated and Added robots.txt file
  robots.txt
Labels: enhancement

#51 Changed Inline style in footer to external stylesheet
  AgroEagel.html
  AgroGuard.html
  AgroMate.html
  about.html
  blog/blog-main.html
  blog/blog-page-2.html
  blog/blog-page.html
  career.html
  catalog.html
  contact.html
  css/style.css
  index.html
Labels: bug

#52 Added keywords to meta tag
  AgroEagel.html
  AgroGuard.html
  AgroMate.html
  about.html
  blog/blog-main.html
  blog/blog-page-2.html
  blog/blog-page.html
  career.html
  catalog.html
  contact.html
  css/style.css
  index.html
Labels: documentation, enhancement

#63 update the traceability page
  .gitignore
  css/style.css
  images/traceability-banner1.png
  traceability.html
Labels: bug, enhancement

#65 Update iafn.png
  images/iafn.png
Labels: bug, enhancement
