Repository Elzian-Agro/Agro, pull requests merged in 2022-01, with the labels that each got.

#69 Copy Right Year changed #68
  AgroEagel.html
  AgroGuard.html
  AgroMate.html
  about.html
  blog/blog-main.html
  blog/blog-page-2.html
  blog/blog-page-3.html
  blog/blog-page.html
  career.html
  catalog.html
  contact.html
  index.html
  traceability.html
Labels: good first issue

#71 Updated Facebook page link
  AgroEagel.html
  AgroGuard.html
  AgroMate.html
  about.html
  blog/blog-main.html
  blog/blog-page-2.html
  blog/blog-page-3.html
  blog/blog-page.html
  career.html
  catalog.html
  contact.html
  index.html
  traceability.html
Labels: bug

#66 Contact page updated as per requirement
  contact.html
  css/style.css
  images/greenclock.png
  images/greentlephone.png
  images/greenvisit.png
Labels: bug, enhancement

#73 Made Notify me button worked
  index.html
Labels: bug

#79 Updated talk to us button
  index.html
Labels: bug

#84 update the affiliates and remove the comments
  AgroEagel.html
  AgroGuard.html
  AgroMate.html
  about.html
  catalog.html
  contact.html
  images/Ericsson-Logo.jpg
  images/founder.png
  index.html
  traceability.html
Labels: bug

#86 Issue #85 solved
  AgroEagel.html
  AgroGuard.html
  AgroMate.html
  about.html
  blog/blog-main.html
  blog/blog-page-2.html
  blog/blog-page-3.html
  blog/blog-page-4.html
  blog/blog-page-5.html
  blog/blog-page.html
  career.html
  catalog.html
  contact.html
  index.html
  traceability.html
Labels: bug, enhancement

#87 add related blogs and fix the link issue
  blog/blog-page-2.html
  blog/blog-page-3.html
  blog/blog-page-4.html
  blog/blog-page-5.html
  blog/blog-page.html
  css/style.css
Labels: bug

#89 Update blog-page-4.html
  blog/blog-page-4.html
Labels: bug

#91 change files
  blog/blog-page-2.html
  blog/blog-page-3.html
  blog/blog-page-5.html
  blog/blog-page.html
  images/Madhurya Blog - 2.png
Labels: bug

#92 Dev
  blog/blog-main.html
  blog/blog-page-2.html
  blog/blog-page-3.html
  blog/blog-page-4.html
  blog/blog-page-5.html
  blog/blog-page.html
Labels: bug

#95 Blog sharing issue for linkedin
  blog/blog-page-2.html
  blog/blog-page-3.html
  blog/blog-page-4.html
  blog/blog-page-5.html
  blog/blog-page.html
Labels: bug

#100 All Issues solved
  AgroEagel.html
  AgroGuard.html
  AgroMate.html
  about.html
  blog/blog-main.html
  blog/blog-page-2.html
  blog/blog-page-3.html
  blog/blog-page-4.html
  blog/blog-page-5.html
  blog/blog-page.html
  career.html
  catalog.html
  contact.html
  images/Madhurya Blog-2.png
  index.html
  traceability.html
Labels: bug, enhancement

#102 Change the about us page.
  about.html
  career.html
  docs/Blockchain_Developer_Internship.pdf
  docs/Mobile_App_Developer_Internship.pdf
  images/wayamba-logo.png
Labels: bug, enhancement

#106 Added underline and changed Instagram link across all file
  AgroEagel.html
  AgroGuard.html
  AgroMate.html
  about.html
  blog/blog-main.html
  blog/blog-page-2.html
  blog/blog-page-3.html
  blog/blog-page-4.html
  blog/blog-page-5.html
  blog/blog-page.html
  career.html
  catalog.html
  contact.html
  index.html
  traceability.html
Labels: bug, enhancement

#120 Removed Typo Issue #108
  index.html
Labels: bug

#123 Added link in about us section and did changes in social media links
  AgroEagel.html
  AgroGuard.html
  AgroMate.html
  about.html
  blog/blog-main.html
  blog/blog-page-2.html
  blog/blog-page-3.html
  blog/blog-page-4.html
  blog/blog-page-5.html
  blog/blog-page.html
  career.html
  catalog.html
  contact.html
  index.html
  traceability.html
Labels: bug, enhancement

#124 Update logo to respected pages
  AgroEagel.html
  AgroGuard.html
  AgroMate.html
  about.html
  blog/blog-main.html
  blog/blog-page-2.html
  blog/blog-page-3.html
  blog/blog-page-4.html
  blog/blog-page-5.html
  blog/blog-page.html
  career.html
  catalog.html
  contact.html
  css/navstyle.css
  css/style.css
  index.html
  traceability.html
Labels: enhancement
