Repository Elzian-Agro/Agro, pull requests merged in 2022-06, with the labels that each got.

#193 Development
  about.html
  blog/blog-main.html
  blog/blog-page-13.html
  css/style.css
  images/Madhurya-blog-13-ItAgriculture-Main-Picture.jpg
  images/Madhurya-blog-13-ItAgriculture-Sub-Picture.jpg
  images/awards/CYA(1).png
  images/awards/cya.png
  images/blog-main-background-image.jpg
  images/blog-main-background-image1.jpg
Labels: bug

#194 Advisory board and Director board to about us page
  about.html
  blog/blog-main.html
  css/style.css
  images/AdvisoryBoard/Wima.png
  images/AdvisoryBoard/dam.png
  images/AdvisoryBoard/mii.png
  images/AdvisoryBoard/nad.png
  images/AdvisoryBoard/pra.png
  images/AdvisoryBoard/rani.png
  images/AdvisoryBoard/supu.png
  images/AdvisoryBoard/tha.png
  images/AdvisoryBoard/uda.png
  images/ExecutiveBoard/lil.png
  images/ExecutiveBoard/pan.png
  images/ExecutiveBoard/ri.png
  images/blog-banner.jpg
Labels: enhancement

#196 blog page 13 changed meta content
  blog/blog-page-13.html
Labels: bug

#197 Dev
  blog/blog-page-13.html
Labels: bug

#198 blog page 14 by Yohan Fernando
  blog/blog-main.html
  blog/blog-page-14.html
  images/Yohan Fernando.jpg
  images/Yohan-blog-14-agriculturalAutomation-MainPicture.jpg
Labels: enhancement

#202 small change
  about.html
Labels: documentation

#204 Blog 15 publish
  blog/blog-main.html
  blog/blog-page-15.html
  images/Ranil-blog-15-appreciatingSoil-MainPicture.jpg
  images/Ranil-blog-15-appreciatingSoil-SubPicture1.jpg
  images/Ranil-blog-15-appreciatingSoil-SubPicture2.jpg
Labels: enhancement

#206 Blog 16 page publish
  blog/blog-main.html
  blog/blog-page-16.html
  images/Thejani Mahanama.png
  images/Thejani-blog-16-agricultureWithDrone-MainPicture.jpg
Labels: enhancement
