Repository Elzian-Agro/Agro, pull requests merged in 2022-05, with the labels that each got.

#172 In about page first line edited.
  about.html
Labels: bug

#173 update the website with new product images
  about.html
  images/ag-detector-1.jpg
  images/ag-detector-2.jpg
  index.html
Labels: bug, enhancement

#177 New Changes
  AgroMate.html
  css/style.css
  index.html
Labels: enhancement

#184 blog-page-11 organic soil
  blog/blog-main.html
  blog/blog-page-11.html
  css/style.css
  images/Kulakshi blog-11-OrganicSoil Main Picture.jpg
  images/Kulakshi blog-11-OrganicSoil Sub Picture.jpg
Labels: enhancement

#185 Blog 11
  blog/blog-main.html
  blog/blog-page-11.html
  css/style.css
  images/Kulakshi blog-11-OrganicSoil Main Picture.jpg
  images/Kulakshi blog-11-OrganicSoil Sub Picture.jpg
Labels: enhancement

#186 blog-page-12 SL growth proposal by Dr. Ranil Senanayake
  blog/blog-main.html
  blog/blog-page-12.html
  images/Ranil-blog-12-SlGrowth-Main-Picture.jpg
  images/Ranil-blog-12-SlGrowth-Sub-Picture.jpg
Labels: enhancement

#187 Blog page 12
  blog/blog-main.html
  blog/blog-page-12.html
  images/Ranil-blog-12-SlGrowth-Main-Picture.jpg
  images/Ranil-blog-12-SlGrowth-Sub-Picture.jpg
Labels: enhancement

#189 image changed
  css/home-baner.css
  css/style.css
  images/inquire-modal-bg.jpg
Labels: enhancement
